.PHONY: clean All

All:
	@echo "----------Building project:[ CreateAndIterate - Debug ]----------"
	@cd "CreateAndIterate" && "$(MAKE)" -f  "CreateAndIterate.mk"
clean:
	@echo "----------Cleaning project:[ CreateAndIterate - Debug ]----------"
	@cd "CreateAndIterate" && "$(MAKE)" -f  "CreateAndIterate.mk" clean
